-----[ 초기화 ]-----------------------------------------------------------

--테이블
DROP TABLE ITEM_ORDER CASCADE CONSTRAINTS;
DROP TABLE CUSTOMER CASCADE CONSTRAINTS;
DROP TABLE ITEM_RELEASE CASCADE CONSTRAINTS;
DROP TABLE SELL CASCADE CONSTRAINTS;
DROP TABLE ITEM CASCADE CONSTRAINTS;
DROP TABLE ITEM_CATEGORY CASCADE CONSTRAINTS;
DROP TABLE ITEM_CATEGORY_LIST CASCADE CONSTRAINTS;

DROP TABLE APPROVE CASCADE CONSTRAINTS;
DROP TABLE APPROVE_STATUS CASCADE CONSTRAINTS;
DROP TABLE APPROVE_DOCUMENT CASCADE CONSTRAINTS;

DROP TABLE COMMUTE_OFF CASCADE CONSTRAINTS;
DROP TABLE COMMUTE_ON CASCADE CONSTRAINTS;
DROP TABLE EMP_ATTEMDANCE CASCADE CONSTRAINTS;
DROP TABLE ATTEMDANCE CASCADE CONSTRAINTS;
DROP TABLE ATTEMDANCE_TYPE CASCADE CONSTRAINTS;

DROP TABLE APPOINTMENT_TYPE CASCADE CONSTRAINTS;
DROP TABLE PERSONNEL_APPOINTMENT CASCADE CONSTRAINTS;

DROP TABLE EMPLOYEE CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEE_RANK CASCADE CONSTRAINTS;
DROP TABLE DEPARTMENT CASCADE CONSTRAINTS;

DROP TABLE NOTICE CASCADE CONSTRAINTS;

DROP TABLE MESSAGE_DATA CASCADE CONSTRAINTS;



--시퀀스

DROP SEQUENCE SEQ_ATNO;
DROP SEQUENCE SEQ_ANO;

DROP SEQUENCE SEQ_APPORVE_NO;
DROP SEQUENCE SEQ_EMPLOYEE_NO;

DROP SEQUENCE SEQ_ITEM_CATEGORY_NO;
DROP SEQUENCE SEQ_ITEM_NO;
DROP SEQUENCE SEQ_ITEM_RELEASE_NO;
DROP SEQUENCE SEQ_CUSTOMER_NO;
DROP SEQUENCE SEQ_ITEM_ORDER_NO;
DROP SEQUENCE SEQ_ITEM_SELL_NO;

DROP SEQUENCE SEQ_NOTICE_NO;

DROP SEQUENCE SEQ_APPOINTMENT_NO;


-----[ 부서 ]-----------------------------------------------------------
CREATE TABLE DEPARTMENT ( 
    DEPT_CODE VARCHAR2(3) PRIMARY KEY,
    DEPT_NAME VARCHAR2(100) NOT NULL,
    PARENT_DEPT VARCHAR2(1)
);
COMMENT ON COLUMN DEPARTMENT.DEPT_CODE IS '부서 코드';
COMMENT ON COLUMN DEPARTMENT.DEPT_NAME IS '부서명';
COMMENT ON COLUMN DEPARTMENT.PARENT_DEPT IS '상급 부서';

INSERT ALL
    INTO DEPARTMENT VALUES('H','인사부',NULL)
    INTO DEPARTMENT VALUES('H1','인사1팀','H')
    INTO DEPARTMENT VALUES('H2','인사2팀','H')
    
    INTO DEPARTMENT VALUES('S','영업부',NULL)
    INTO DEPARTMENT VALUES('S1','영업1팀','S')
    INTO DEPARTMENT VALUES('S2','영업2팀','S')
    INTO DEPARTMENT VALUES('P','기획팀','S')
    INTO DEPARTMENT VALUES('CS','고객지원팀','S')
    INTO DEPARTMENT VALUES('PR','홍보팀','S')
    
    INTO DEPARTMENT VALUES('A','회계부',NULL)
    INTO DEPARTMENT VALUES('A1','회계팀','A')
    
    INTO DEPARTMENT VALUES('D','개발부',NULL)
    INTO DEPARTMENT VALUES('D1','개발팀','D')
    
    INTO DEPARTMENT VALUES('ND','미배치',NULL)
    INTO DEPARTMENT VALUES('#','관리자',NULL)
SELECT * FROM DUAL;

-----[ 직급 ]-----------------------------------------------------------
CREATE TABLE EMPLOYEE_RANK ( 
    EMP_RANK VARCHAR2(2) PRIMARY KEY,
    RANK_NAME VARCHAR2(100)
);
COMMENT ON COLUMN EMPLOYEE_RANK.EMP_RANK IS '직급 코드';
COMMENT ON COLUMN EMPLOYEE_RANK.RANK_NAME IS '직급명';

INSERT ALL
    INTO EMPLOYEE_RANK VALUES('R1','사장')
    INTO EMPLOYEE_RANK VALUES('R2','부장')
    INTO EMPLOYEE_RANK VALUES('R3','팀장')
    INTO EMPLOYEE_RANK VALUES('R4','과장')
    INTO EMPLOYEE_RANK VALUES('R5','차장')
    INTO EMPLOYEE_RANK VALUES('R6','대리')
    INTO EMPLOYEE_RANK VALUES('R7','사원')
    INTO EMPLOYEE_RANK VALUES('##','관리자')
SELECT * FROM DUAL;


-----[ 사원 ]-----------------------------------------------------------
CREATE SEQUENCE SEQ_EMPLOYEE_NO
START WITH 10000
NOCACHE;

CREATE TABLE EMPLOYEE (            
    EMP_NO NUMBER PRIMARY KEY,
    EMP_PWD VARCHAR2(200),
    EMP_RANK VARCHAR2(2) DEFAULT 'R7',  
    DEPT_CODE VARCHAR2(3) DEFAULT 'ND',
    EMP_NAME VARCHAR2(100) NOT NULL,
    AGE NUMBER,
    PHONE VARCHAR2(13),
    EMAIL VARCHAR2(100),
    ADDRESS VARCHAR2(4000),
    BIRTHDAY DATE,
    VACATION VARCHAR2(5),
    JOIN_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY(EMP_RANK) REFERENCES EMPLOYEE_RANK(EMP_RANK) ON DELETE SET NULL,
    FOREIGN KEY(DEPT_CODE) REFERENCES DEPARTMENT(DEPT_CODE) ON DELETE SET NULL
);
COMMENT ON COLUMN EMPLOYEE.EMP_NO IS '사원번호';
COMMENT ON COLUMN EMPLOYEE.EMP_PWD IS '비밀번호';
COMMENT ON COLUMN EMPLOYEE.EMP_RANK IS '직급 코드';
COMMENT ON COLUMN EMPLOYEE.DEPT_CODE IS '부서 코드';
COMMENT ON COLUMN EMPLOYEE.EMP_NAME IS '사원명';
COMMENT ON COLUMN EMPLOYEE.AGE IS '나이';
COMMENT ON COLUMN EMPLOYEE.PHONE IS '전화';
COMMENT ON COLUMN EMPLOYEE.EMAIL IS '이메일';
COMMENT ON COLUMN EMPLOYEE.ADDRESS IS '주소';
COMMENT ON COLUMN EMPLOYEE.BIRTHDAY IS '생년월일';
COMMENT ON COLUMN EMPLOYEE.VACATION IS '연차갯수';
COMMENT ON COLUMN EMPLOYEE.JOIN_DATE IS '입사일';

INSERT INTO EMPLOYEE(EMP_NO,EMP_PWD,EMP_RANK,DEPT_CODE,EMP_NAME)
VALUES(99,'$2a$10$c388suJqsB2cNC57f/sIbuqmhxjd6uS9OTaoBLv684KV7tROLvtsu','##','#','관리자');

-----[ 발령 유형 ]-----------------------------------------------------------
-- 발령번호 시퀀스 생성
CREATE SEQUENCE SEQ_APPOINTMENT_NO
   START WITH 1
   NOCACHE;

-- 발령구분 코드 테이블
CREATE TABLE APPOINTMENT_TYPE (
   APPOINTMENT_TYPE_CODE NUMBER PRIMARY KEY,      
   APPOINTMENT_TYPE_NAME VARCHAR2(100)                  
);
COMMENT ON COLUMN APPOINTMENT_TYPE.APPOINTMENT_TYPE_CODE IS '발령 유형 코드';
COMMENT ON COLUMN APPOINTMENT_TYPE.APPOINTMENT_TYPE_NAME IS '발령 유형';
INSERT ALL
    INTO APPOINTMENT_TYPE VALUES(1,'입사')
    INTO APPOINTMENT_TYPE VALUES(2,'직급 변경')
    INTO APPOINTMENT_TYPE VALUES(3,'부서 변경')
    INTO APPOINTMENT_TYPE VALUES(4,'퇴사')
SELECT * FROM DUAL;

-- 인사발령 테이블
CREATE TABLE PERSONNEL_APPOINTMENT (
    APPOINTMENT_NO VARCHAR2(20) PRIMARY KEY,
    EMP_NO NUMBER,
    APPOINTMENT_DATE VARCHAR2(20) DEFAULT TO_CHAR(SYSDATE, 'YYYY-MM-DD'),
    APPOINTMENT_TYPE_CODE NUMBER,
    NEW_DEPT VARCHAR2(3),
    NEW_RANK VARCHAR2(2)
);

COMMENT ON COLUMN PERSONNEL_APPOINTMENT.APPOINTMENT_NO IS '발령번호';
COMMENT ON COLUMN PERSONNEL_APPOINTMENT.EMP_NO IS '사원번호';
COMMENT ON COLUMN PERSONNEL_APPOINTMENT.APPOINTMENT_DATE IS '발령일자';
COMMENT ON COLUMN PERSONNEL_APPOINTMENT.APPOINTMENT_TYPE_CODE IS '발령 유형 코드';
COMMENT ON COLUMN PERSONNEL_APPOINTMENT.NEW_DEPT IS '이동 부서';
COMMENT ON COLUMN PERSONNEL_APPOINTMENT.NEW_RANK IS '새 직급';



-----[ 근태 분류 ]-----------------------------------------------------------
--근태 분류 코드
CREATE SEQUENCE SEQ_ATNO
START WITH 100
NOCACHE;


CREATE TABLE ATTEMDANCE_TYPE(
    ATT_TYPE_CODE NUMBER PRIMARY KEY,
    ATT_TYPE_NAME VARCHAR2(100) NOT NULL
);

COMMENT ON COLUMN ATTEMDANCE_TYPE.ATT_TYPE_CODE IS '분류 코드';
COMMENT ON COLUMN ATTEMDANCE_TYPE.ATT_TYPE_NAME IS '분류명';

INSERT INTO ATTEMDANCE_TYPE
VALUES(SEQ_ATNO.NEXTVAL, '연차');


-----[ 세부 분류 ]-----------------------------------------------------------
--근태 세부 분류 코드
CREATE SEQUENCE SEQ_ANO
START WITH 1000
NOCACHE;

CREATE TABLE ATTEMDANCE(
    ATT_CODE NUMBER PRIMARY KEY,
    ATT_TYPE_CODE NUMBER NOT NULL,
    ATT_NAME VARCHAR2(100) NOT NULL,
    ATT_COUNT NUMBER NOT NULL,
    ATT_STATE VARCHAR2(1) DEFAULT 'Y' CHECK(ATT_STATE IN('Y','N')),
    FOREIGN KEY(ATT_TYPE_CODE) REFERENCES ATTEMDANCE_TYPE(ATT_TYPE_CODE)
);

COMMENT ON COLUMN ATTEMDANCE.ATT_CODE IS '세부 코드';
COMMENT ON COLUMN ATTEMDANCE.ATT_TYPE_CODE IS '분류 코드';
COMMENT ON COLUMN ATTEMDANCE.ATT_NAME IS '세부명';
COMMENT ON COLUMN ATTEMDANCE.ATT_COUNT IS '근태수';

INSERT INTO ATTEMDANCE
VALUES(SEQ_ANO.NEXTVAL, 100, '2024연차', 1.0, DEFAULT);


-----[ 사원 근태 ]-----------------------------------------------------------
CREATE TABLE EMP_ATTEMDANCE(
    EMP_ATT_TIME DATE NOT NULL,
    ATT_CODE NUMBER NOT NULL,
    EMP_NO NUMBER NOT NULL,
    EMP_ATT_COUNT NUMBER NOT NULL,
    INPUT_DATE DATE DEFAULT SYSDATE,
    EMP_ATT_STATE VARCHAR(1) CHECK(EMP_ATT_STATE IN ('Y','N')),
    FOREIGN KEY(ATT_CODE) REFERENCES ATTEMDANCE(ATT_CODE),
    FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEE(EMP_NO)
);

COMMENT ON COLUMN EMP_ATTEMDANCE.EMP_ATT_TIME IS '근태일';
COMMENT ON COLUMN EMP_ATTEMDANCE.ATT_CODE IS '근태 세부 코드';
COMMENT ON COLUMN EMP_ATTEMDANCE.EMP_NO IS '사원 번호';
COMMENT ON COLUMN EMP_ATTEMDANCE.EMP_ATT_COUNT IS '근태수';
COMMENT ON COLUMN EMP_ATTEMDANCE.INPUT_DATE IS '입력일';

INSERT INTO EMP_ATTEMDANCE
VALUES('2024/12/12', 1000, 10000, 1.0, DEFAULT, NULL);


-----[ 출근 ]-----------------------------------------------------------
CREATE TABLE COMMUTE_ON(
    EMP_NO NUMBER NOT NULL,
    COM_START DATE DEFAULT SYSDATE,
    FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEE(EMP_NO)
);


-----[ 퇴근 ]-----------------------------------------------------------
CREATE TABLE COMMUTE_OFF(
    EMP_NO NUMBER NOT NULL,
    COM_END DATE DEFAULT SYSDATE,
    FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEE(EMP_NO)
);



-----[ 전자 결재 ]-----------------------------------------------------------
CREATE SEQUENCE SEQ_APPORVE_NO
START WITH 1
NOCACHE;

CREATE TABLE APPROVE_DOCUMENT (
     DO_NO VARCHAR2(5) PRIMARY KEY,
     DO_LIST VARCHAR2(20),
     DO_CONTENT VARCHAR2(4000)
);
COMMENT ON COLUMN APPROVE_DOCUMENT.DO_NO IS '양식 번호';
COMMENT ON COLUMN APPROVE_DOCUMENT.DO_LIST IS '서류 양식';
COMMENT ON COLUMN APPROVE_DOCUMENT.DO_CONTENT IS '서류 내용';

CREATE TABLE APPROVE_STATUS(
   STATUS_CODE VARCHAR2(1) PRIMARY KEY
  ,STATUS VARCHAR2(20)
   );
   
COMMENT ON COLUMN APPROVE_STATUS.STATUS_CODE IS '상태 코드';
COMMENT ON COLUMN APPROVE_STATUS.STATUS IS '상태';

CREATE TABLE APPROVE(
   AP_NO VARCHAR2(20) PRIMARY KEY,
   EMP_NO NUMBER,
   AP_CREATE_DATE DATE DEFAULT SYSDATE,
   AP_TITLE VARCHAR2(100),
   AP_CONTENT VARCHAR2(4000),
   STATUS_CODE VARCHAR2(1) DEFAULT 0,
   AP_MASTER NUMBER,
   FOREIGN KEY(STATUS_CODE) REFERENCES APPROVE_STATUS(STATUS_CODE),
   FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEE(EMP_NO)
);

COMMENT ON COLUMN APPROVE.AP_NO IS '번호';
COMMENT ON COLUMN APPROVE.EMP_NO IS '사원 번호';
COMMENT ON COLUMN APPROVE.AP_CREATE_DATE IS '작성일';
COMMENT ON COLUMN APPROVE.AP_TITLE IS '결재 제목';
COMMENT ON COLUMN APPROVE.AP_CONTENT IS '결재 내용';
COMMENT ON COLUMN APPROVE.STATUS_CODE IS '상태 코드';
COMMENT ON COLUMN APPROVE.AP_MASTER IS '결재자';



-----[ 제품 ]-----------------------------------------------------------
CREATE SEQUENCE SEQ_ITEM_NO
START WITH 1
NOCACHE;

CREATE TABLE ITEM(
    ITEM_CODE NUMBER PRIMARY KEY,
    ITEM_NAME VARCHAR2(2000) NOT NULL,
    ITEM_PRICE NUMBER NOT NULL,
    ITEM_COUNT NUMBER DEFAULT 0
);
COMMENT ON COLUMN ITEM.ITEM_CODE IS '제품 코드';
COMMENT ON COLUMN ITEM.ITEM_NAME IS '이름';
COMMENT ON COLUMN ITEM.ITEM_PRICE IS '가격';
COMMENT ON COLUMN ITEM.ITEM_COUNT IS '수량';


-----[ 제품 카테고리 목록 ]-----------------------------------------------------------
CREATE SEQUENCE SEQ_ITEM_CATEGORY_NO
START WITH 1
NOCACHE;

CREATE TABLE ITEM_CATEGORY_LIST(
    ITEM_CATEGORY_NO NUMBER PRIMARY KEY,
    ITEM_CATEGORY_NAME VARCHAR2(2000) NOT NULL
);
COMMENT ON COLUMN ITEM_CATEGORY_LIST.ITEM_CATEGORY_NO IS '카테고리 번호';
COMMENT ON COLUMN ITEM_CATEGORY_LIST.ITEM_CATEGORY_NAME IS '카테고리 이름';


-----[ 제품 카테고리 ]-----------------------------------------------------------
CREATE TABLE ITEM_CATEGORY(
    ITEM_CODE NUMBER,
    ITEM_CATEGORY_NO NUMBER,
    FOREIGN KEY(ITEM_CODE) REFERENCES ITEM(ITEM_CODE) ON DELETE CASCADE,
    FOREIGN KEY(ITEM_CATEGORY_NO) REFERENCES ITEM_CATEGORY_LIST(ITEM_CATEGORY_NO) ON DELETE CASCADE
);
COMMENT ON COLUMN ITEM_CATEGORY.ITEM_CODE IS '제품 코드';
COMMENT ON COLUMN ITEM_CATEGORY.ITEM_CATEGORY_NO IS '카테고리 번호';


-----[ 판매 ]-----------------------------------------------------------
CREATE SEQUENCE SEQ_ITEM_SELL_NO
START WITH 1
NOCACHE;
CREATE TABLE SELL(
    SELL_NO NUMBER,
    ITEM_CODE NUMBER,
    SELL_COUNT NUMBER NOT NULL,
    SELL_PRICE NUMBER NOT NULL,
    SELL_DATE VARCHAR2(20) DEFAULT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'),
    RELEASE_STATUS VARCHAR2(1) DEFAULT 'N' CHECK(RELEASE_STATUS IN('N','Y')),
    FOREIGN KEY(ITEM_CODE) REFERENCES ITEM(ITEM_CODE)
);
COMMENT ON COLUMN SELL.SELL_NO IS '판매 번호';
COMMENT ON COLUMN SELL.SELL_COUNT IS '수량';
COMMENT ON COLUMN SELL.SELL_PRICE IS '가격';
COMMENT ON COLUMN SELL.SELL_DATE IS '판매날짜';
COMMENT ON COLUMN SELL.ITEM_CODE IS '물품 코드';
COMMENT ON COLUMN SELL.RELEASE_STATUS IS '출하 여부';


-----[ 출하 ]-----------------------------------------------------------
CREATE SEQUENCE SEQ_ITEM_RELEASE_NO
START WITH 1
NOCACHE;

CREATE TABLE ITEM_RELEASE(
    RELEASE_NO NUMBER PRIMARY KEY,
    RELEASE_COUNT NUMBER NOT NULL,
    RELEASE_DATE VARCHAR2(20) DEFAULT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'),
    ITEM_CODE NUMBER,
    FOREIGN KEY(ITEM_CODE) REFERENCES ITEM(ITEM_CODE)
);
COMMENT ON COLUMN ITEM_RELEASE.RELEASE_NO IS '출하 번호';
COMMENT ON COLUMN ITEM_RELEASE.RELEASE_COUNT IS '출하 수량';
COMMENT ON COLUMN ITEM_RELEASE.RELEASE_DATE IS '출하 날짜';
COMMENT ON COLUMN ITEM_RELEASE.ITEM_CODE IS '물품 코드';


-----[ 거래처 ]-----------------------------------------------------------
CREATE SEQUENCE SEQ_CUSTOMER_NO
START WITH 1
NOCACHE;

CREATE TABLE CUSTOMER(
    CUSTOMER_NO NUMBER PRIMARY KEY,
    CUSTOMER_NAME VARCHAR2(2000) NOT NULL,
    CUSTOMER_TEL VARCHAR2(15),
    CUSTOMER_ADDRESS VARCHAR2(1000)
);
COMMENT ON COLUMN CUSTOMER.CUSTOMER_NO IS '거래처 코드';
COMMENT ON COLUMN CUSTOMER.CUSTOMER_NAME IS '거래처명';
COMMENT ON COLUMN CUSTOMER.CUSTOMER_TEL IS '거래처 전화번호';
COMMENT ON COLUMN CUSTOMER.CUSTOMER_ADDRESS IS '거래처 주소';


-----[ 발주 ]-----------------------------------------------------------
CREATE SEQUENCE SEQ_ITEM_ORDER_NO
START WITH 1
NOCACHE;

CREATE TABLE ITEM_ORDER(
    ORDER_NO NUMBER PRIMARY KEY,
    CUSTOMER_NO NUMBER,
    ITEM_CODE NUMBER,
    ORDER_COUNT NUMBER NOT NULL,
    ORDER_PRICE NUMBER NOT NULL,
    ORDER_DATE VARCHAR2(20) DEFAULT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'),
    EMP_NO NUMBER,
    FOREIGN KEY(CUSTOMER_NO) REFERENCES CUSTOMER(CUSTOMER_NO) ON DELETE SET NULL,
    FOREIGN KEY(ITEM_CODE) REFERENCES ITEM(ITEM_CODE),
    FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEE(EMP_NO)
);
COMMENT ON COLUMN ITEM_ORDER.ORDER_NO IS '발주 번호';
COMMENT ON COLUMN ITEM_ORDER.CUSTOMER_NO IS '거래처 코드';
COMMENT ON COLUMN ITEM_ORDER.ITEM_CODE IS '물품 코드';
COMMENT ON COLUMN ITEM_ORDER.ORDER_COUNT IS '수량';
COMMENT ON COLUMN ITEM_ORDER.ORDER_PRICE IS '가격';
COMMENT ON COLUMN ITEM_ORDER.ORDER_DATE IS '날짜';
COMMENT ON COLUMN ITEM_ORDER.EMP_NO IS '담당자';


-----[ 공지 ]-----------------------------------------------------------
CREATE SEQUENCE SEQ_NOTICE_NO
START WITH 1
NOCACHE;

CREATE TABLE NOTICE(
    NOTICE_NO NUMBER PRIMARY KEY,
    NOTICE_WRITER NUMBER,
    NOTICE_TITLE VARCHAR2(2000),
    NOTICE_CONTENT VARCHAR2(4000),
    NOTICE_COUNT NUMBER,
    CREATE_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY(NOTICE_WRITER) REFERENCES EMPLOYEE(EMP_NO)
);
COMMENT ON COLUMN NOTICE.NOTICE_NO IS '공지 번호';
COMMENT ON COLUMN NOTICE.NOTICE_WRITER IS '작성자';
COMMENT ON COLUMN NOTICE.NOTICE_TITLE IS '제목';
COMMENT ON COLUMN NOTICE.NOTICE_CONTENT IS '내용';
COMMENT ON COLUMN NOTICE.NOTICE_COUNT IS '조회수';
COMMENT ON COLUMN NOTICE.CREATE_DATE IS '작성일';




-----[ 메시지 데이터 ]-----------------------------------------------------------
CREATE TABLE MESSAGE_DATA(
    SEND NUMBER NOT NULL,
    RECEIVE NUMBER NOT NULL,
    MESSAGE VARCHAR2(4000),
    READ_MSG VARCHAR2(1) DEFAULT 'N' CHECK(READ_MSG IN('Y','N')),
    SEND_TIME VARCHAR2(20) DEFAULT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS')
);
COMMENT ON COLUMN MESSAGE_DATA.SEND IS '송신자';
COMMENT ON COLUMN MESSAGE_DATA.RECEIVE IS '수신자';
COMMENT ON COLUMN MESSAGE_DATA.MESSAGE IS '메시지';
COMMENT ON COLUMN MESSAGE_DATA.READ_MSG IS '확인여부';
COMMENT ON COLUMN MESSAGE_DATA.SEND_TIME IS '전송시간';


-------------------더미데이터------------------------
--거래처 더미데이터
Insert into ERP.CUSTOMER (CUSTOMER_NO,CUSTOMER_NAME,CUSTOMER_TEL,CUSTOMER_ADDRESS) values (SEQ_CUSTOMER_NO.NEXTVAL,'풀무원',null,null);
Insert into ERP.CUSTOMER (CUSTOMER_NO,CUSTOMER_NAME,CUSTOMER_TEL,CUSTOMER_ADDRESS) values (SEQ_CUSTOMER_NO.NEXTVAL,'오뚜기',null,null);
Insert into ERP.CUSTOMER (CUSTOMER_NO,CUSTOMER_NAME,CUSTOMER_TEL,CUSTOMER_ADDRESS) values (SEQ_CUSTOMER_NO.NEXTVAL,'빙그레',null,null);
Insert into ERP.CUSTOMER (CUSTOMER_NO,CUSTOMER_NAME,CUSTOMER_TEL,CUSTOMER_ADDRESS) values (SEQ_CUSTOMER_NO.NEXTVAL,'샘표',null,null);
Insert into ERP.CUSTOMER (CUSTOMER_NO,CUSTOMER_NAME,CUSTOMER_TEL,CUSTOMER_ADDRESS) values (SEQ_CUSTOMER_NO.NEXTVAL,'동서식품',null,null);
Insert into ERP.CUSTOMER (CUSTOMER_NO,CUSTOMER_NAME,CUSTOMER_TEL,CUSTOMER_ADDRESS) values (SEQ_CUSTOMER_NO.NEXTVAL,'남양유업',null,null);
Insert into ERP.CUSTOMER (CUSTOMER_NO,CUSTOMER_NAME,CUSTOMER_TEL,CUSTOMER_ADDRESS) values (SEQ_CUSTOMER_NO.NEXTVAL,'메일유업',null,null);
Insert into ERP.CUSTOMER (CUSTOMER_NO,CUSTOMER_NAME,CUSTOMER_TEL,CUSTOMER_ADDRESS) values (SEQ_CUSTOMER_NO.NEXTVAL,'건국유업',null,null);
Insert into ERP.CUSTOMER (CUSTOMER_NO,CUSTOMER_NAME,CUSTOMER_TEL,CUSTOMER_ADDRESS) values (SEQ_CUSTOMER_NO.NEXTVAL,'롯데칠성음료',null,null);
Insert into ERP.CUSTOMER (CUSTOMER_NO,CUSTOMER_NAME,CUSTOMER_TEL,CUSTOMER_ADDRESS) values (SEQ_CUSTOMER_NO.NEXTVAL,'해태제과식품',null,null);
Insert into ERP.CUSTOMER (CUSTOMER_NO,CUSTOMER_NAME,CUSTOMER_TEL,CUSTOMER_ADDRESS) values (SEQ_CUSTOMER_NO.NEXTVAL,'하림',null,null);
Insert into ERP.CUSTOMER (CUSTOMER_NO,CUSTOMER_NAME,CUSTOMER_TEL,CUSTOMER_ADDRESS) values (SEQ_CUSTOMER_NO.NEXTVAL,'선진',null,null);
Insert into ERP.CUSTOMER (CUSTOMER_NO,CUSTOMER_NAME,CUSTOMER_TEL,CUSTOMER_ADDRESS) values (SEQ_CUSTOMER_NO.NEXTVAL,'롯데제과',null,null);
Insert into ERP.CUSTOMER (CUSTOMER_NO,CUSTOMER_NAME,CUSTOMER_TEL,CUSTOMER_ADDRESS) values (SEQ_CUSTOMER_NO.NEXTVAL,'롯데웰푸드',null,null);
Insert into ERP.CUSTOMER (CUSTOMER_NO,CUSTOMER_NAME,CUSTOMER_TEL,CUSTOMER_ADDRESS) values (SEQ_CUSTOMER_NO.NEXTVAL,'SPC삼립',null,null);
Insert into ERP.CUSTOMER (CUSTOMER_NO,CUSTOMER_NAME,CUSTOMER_TEL,CUSTOMER_ADDRESS) values (SEQ_CUSTOMER_NO.NEXTVAL,'삼양식품',null,null);
Insert into ERP.CUSTOMER (CUSTOMER_NO,CUSTOMER_NAME,CUSTOMER_TEL,CUSTOMER_ADDRESS) values (SEQ_CUSTOMER_NO.NEXTVAL,'CJ',null,null);
Insert into ERP.CUSTOMER (CUSTOMER_NO,CUSTOMER_NAME,CUSTOMER_TEL,CUSTOMER_ADDRESS) values (SEQ_CUSTOMER_NO.NEXTVAL,'CJ제일제당',null,null);
Insert into ERP.CUSTOMER (CUSTOMER_NO,CUSTOMER_NAME,CUSTOMER_TEL,CUSTOMER_ADDRESS) values (SEQ_CUSTOMER_NO.NEXTVAL,'코카콜라',null,null);
Insert into ERP.CUSTOMER (CUSTOMER_NO,CUSTOMER_NAME,CUSTOMER_TEL,CUSTOMER_ADDRESS) values (SEQ_CUSTOMER_NO.NEXTVAL,'오리온',null,null);
Insert into ERP.CUSTOMER (CUSTOMER_NO,CUSTOMER_NAME,CUSTOMER_TEL,CUSTOMER_ADDRESS) values (SEQ_CUSTOMER_NO.NEXTVAL,'현대그린푸드',null,null);
Insert into ERP.CUSTOMER (CUSTOMER_NO,CUSTOMER_NAME,CUSTOMER_TEL,CUSTOMER_ADDRESS) values (SEQ_CUSTOMER_NO.NEXTVAL,'신세계푸드',null,null);
Insert into ERP.CUSTOMER (CUSTOMER_NO,CUSTOMER_NAME,CUSTOMER_TEL,CUSTOMER_ADDRESS) values (SEQ_CUSTOMER_NO.NEXTVAL,'크라운제과',null,null);
Insert into ERP.CUSTOMER (CUSTOMER_NO,CUSTOMER_NAME,CUSTOMER_TEL,CUSTOMER_ADDRESS) values (SEQ_CUSTOMER_NO.NEXTVAL,'삼육식품',null,null);
Insert into ERP.CUSTOMER (CUSTOMER_NO,CUSTOMER_NAME,CUSTOMER_TEL,CUSTOMER_ADDRESS) values (SEQ_CUSTOMER_NO.NEXTVAL,'동아제과',null,null);
Insert into ERP.CUSTOMER (CUSTOMER_NO,CUSTOMER_NAME,CUSTOMER_TEL,CUSTOMER_ADDRESS) values (SEQ_CUSTOMER_NO.NEXTVAL,'팔도',null,null);
Insert into ERP.CUSTOMER (CUSTOMER_NO,CUSTOMER_NAME,CUSTOMER_TEL,CUSTOMER_ADDRESS) values (SEQ_CUSTOMER_NO.NEXTVAL,'한솥',null,null);
Insert into ERP.CUSTOMER (CUSTOMER_NO,CUSTOMER_NAME,CUSTOMER_TEL,CUSTOMER_ADDRESS) values (SEQ_CUSTOMER_NO.NEXTVAL,'웅진식품',null,null);
Insert into ERP.CUSTOMER (CUSTOMER_NO,CUSTOMER_NAME,CUSTOMER_TEL,CUSTOMER_ADDRESS) values (SEQ_CUSTOMER_NO.NEXTVAL,'광동제약',null,null);
Insert into ERP.CUSTOMER (CUSTOMER_NO,CUSTOMER_NAME,CUSTOMER_TEL,CUSTOMER_ADDRESS) values (SEQ_CUSTOMER_NO.NEXTVAL,'농협목우촌',null,null);
Insert into ERP.CUSTOMER (CUSTOMER_NO,CUSTOMER_NAME,CUSTOMER_TEL,CUSTOMER_ADDRESS) values (SEQ_CUSTOMER_NO.NEXTVAL,'사조대림',null,null);


--품목 더미데이터
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '불고기 도시락', 3000, 1234);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '김치볶음밥', 5000, 2345);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '치킨마요 덮밥', 7000, 345);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '햄치즈 샌드위치', 2000, 4567);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '참치김밥', 3000, 890);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '전주비빔밥', 6000, 1567);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '바베큐 치킨 도시락', 4000, 784);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '돈까스 도시락', 5000, 234);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '김밥', 2000, 3000);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '새우볶음밥', 6000, 4100);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '비빔국수', 5000, 1890);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '매운 갈비찜', 7000, 234);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '냉모밀', 4000, 1200);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '잔치국수', 3000, 890);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '치킨너겟', 4000, 2345);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '카레라이스', 5000, 1567);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '오므라이스', 6000, 120);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '해물파전', 3000, 234);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '떡갈비 도시락', 4000, 786);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '새우튀김 도시락', 5000, 910);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '육개장', 4000, 1200);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '순두부찌개', 3000, 2000);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '갈비탕', 7000, 345);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '된장찌개', 3000, 890);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '떡국', 4000, 1345);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '비빔밥', 5000, 1789);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '라면', 2000, 3456);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '짜장면', 4000, 2390);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '짬뽕', 5000, 200);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '우동', 4000, 678);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '소고기 덮밥', 7000, 567);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '된장국', 3000, 980);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '해물 덮밥', 8000, 456);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '불닭볶음면', 2000, 300);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '냉면', 5000, 890);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '떡볶이', 3000, 456);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '순대국', 4000, 2000);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '불고기', 3000, 800);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '삼겹살 도시락', 6000, 123);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '계란찜', 2000, 3456);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '야채볶음밥', 3000, 876);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '콩나물국밥', 4000, 789);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '두부김치', 5000, 432);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '만두', 2000, 2345);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '찜닭', 7000, 678);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '카츠돈', 5000, 1234);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '어묵탕', 4000, 900);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '감자탕', 6000, 1345);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '치즈라면', 3000, 1000);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '깐풍기', 8000, 567);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_PRICE, ITEM_COUNT) VALUES (SEQ_ITEM_NO.NEXTVAL, '도시락', 2000, 890);



-- 카테고리 더미데이터
INSERT INTO ITEM_CATEGORY_LIST VALUES(SEQ_ITEM_CATEGORY_NO.NEXTVAL, '과자');
INSERT INTO ITEM_CATEGORY_LIST VALUES(SEQ_ITEM_CATEGORY_NO.NEXTVAL, '캔디류');
INSERT INTO ITEM_CATEGORY_LIST VALUES(SEQ_ITEM_CATEGORY_NO.NEXTVAL, '츄잉껌');
INSERT INTO ITEM_CATEGORY_LIST VALUES(SEQ_ITEM_CATEGORY_NO.NEXTVAL, '빵류');
INSERT INTO ITEM_CATEGORY_LIST VALUES(SEQ_ITEM_CATEGORY_NO.NEXTVAL, '떡류');
INSERT INTO ITEM_CATEGORY_LIST VALUES(SEQ_ITEM_CATEGORY_NO.NEXTVAL, '아이스크림');
INSERT INTO ITEM_CATEGORY_LIST VALUES(SEQ_ITEM_CATEGORY_NO.NEXTVAL, '샤베트');
INSERT INTO ITEM_CATEGORY_LIST VALUES(SEQ_ITEM_CATEGORY_NO.NEXTVAL, '빙과');
INSERT INTO ITEM_CATEGORY_LIST VALUES(SEQ_ITEM_CATEGORY_NO.NEXTVAL, '식용얼음');
INSERT INTO ITEM_CATEGORY_LIST VALUES(SEQ_ITEM_CATEGORY_NO.NEXTVAL, '코코아가공품');
INSERT INTO ITEM_CATEGORY_LIST VALUES(SEQ_ITEM_CATEGORY_NO.NEXTVAL, '초콜릿');
INSERT INTO ITEM_CATEGORY_LIST VALUES(SEQ_ITEM_CATEGORY_NO.NEXTVAL, '면류');
INSERT INTO ITEM_CATEGORY_LIST VALUES(SEQ_ITEM_CATEGORY_NO.NEXTVAL, '다류');
INSERT INTO ITEM_CATEGORY_LIST VALUES(SEQ_ITEM_CATEGORY_NO.NEXTVAL, '커피');
INSERT INTO ITEM_CATEGORY_LIST VALUES(SEQ_ITEM_CATEGORY_NO.NEXTVAL, '과일.채소류음료');
INSERT INTO ITEM_CATEGORY_LIST VALUES(SEQ_ITEM_CATEGORY_NO.NEXTVAL, '탄산음료');
INSERT INTO ITEM_CATEGORY_LIST VALUES(SEQ_ITEM_CATEGORY_NO.NEXTVAL, '두유');
INSERT INTO ITEM_CATEGORY_LIST VALUES(SEQ_ITEM_CATEGORY_NO.NEXTVAL, '발효음료');
INSERT INTO ITEM_CATEGORY_LIST VALUES(SEQ_ITEM_CATEGORY_NO.NEXTVAL, '소스류');
INSERT INTO ITEM_CATEGORY_LIST VALUES(SEQ_ITEM_CATEGORY_NO.NEXTVAL, '주류');

INSERT INTO ITEM_CATEGORY_LIST VALUES(SEQ_ITEM_CATEGORY_NO.NEXTVAL, '전분');
INSERT INTO ITEM_CATEGORY_LIST VALUES(SEQ_ITEM_CATEGORY_NO.NEXTVAL, '밀가루');
INSERT INTO ITEM_CATEGORY_LIST VALUES(SEQ_ITEM_CATEGORY_NO.NEXTVAL, '견과류');
INSERT INTO ITEM_CATEGORY_LIST VALUES(SEQ_ITEM_CATEGORY_NO.NEXTVAL, '시리얼');
INSERT INTO ITEM_CATEGORY_LIST VALUES(SEQ_ITEM_CATEGORY_NO.NEXTVAL, '농산가공품');
INSERT INTO ITEM_CATEGORY_LIST VALUES(SEQ_ITEM_CATEGORY_NO.NEXTVAL, '햄');
INSERT INTO ITEM_CATEGORY_LIST VALUES(SEQ_ITEM_CATEGORY_NO.NEXTVAL, '소시지');
INSERT INTO ITEM_CATEGORY_LIST VALUES(SEQ_ITEM_CATEGORY_NO.NEXTVAL, '베이컨');
INSERT INTO ITEM_CATEGORY_LIST VALUES(SEQ_ITEM_CATEGORY_NO.NEXTVAL, '건조저장육류');
INSERT INTO ITEM_CATEGORY_LIST VALUES(SEQ_ITEM_CATEGORY_NO.NEXTVAL, '포장육');

INSERT INTO ITEM_CATEGORY_LIST VALUES(SEQ_ITEM_CATEGORY_NO.NEXTVAL, '유제품');
INSERT INTO ITEM_CATEGORY_LIST VALUES(SEQ_ITEM_CATEGORY_NO.NEXTVAL, '어육가공품');
INSERT INTO ITEM_CATEGORY_LIST VALUES(SEQ_ITEM_CATEGORY_NO.NEXTVAL, '젓갈');
INSERT INTO ITEM_CATEGORY_LIST VALUES(SEQ_ITEM_CATEGORY_NO.NEXTVAL, '조미김');
INSERT INTO ITEM_CATEGORY_LIST VALUES(SEQ_ITEM_CATEGORY_NO.NEXTVAL, '즉석식품');
INSERT INTO ITEM_CATEGORY_LIST VALUES(SEQ_ITEM_CATEGORY_NO.NEXTVAL, '냉동식품');



--사원 더미데이터
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_RANK,DEPT_CODE,BIRTHDAY)
VALUES(SEQ_EMPLOYEE_NO.NEXTVAL,'권부장','R2','D',SYSDATE);
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_RANK,DEPT_CODE)
VALUES(SEQ_EMPLOYEE_NO.NEXTVAL,'곽혜민','R7','D');
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_RANK,DEPT_CODE)
VALUES(SEQ_EMPLOYEE_NO.NEXTVAL,'이준영','R7','D');
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_RANK,DEPT_CODE)
VALUES(SEQ_EMPLOYEE_NO.NEXTVAL,'장용민','R7','D');


INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_RANK,DEPT_CODE,BIRTHDAY)
VALUES(SEQ_EMPLOYEE_NO.NEXTVAL,'박부장','R2','H',SYSDATE);
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_RANK,DEPT_CODE,BIRTHDAY)
VALUES(SEQ_EMPLOYEE_NO.NEXTVAL,'윤팀장','R3','H1',SYSDATE);
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_RANK,DEPT_CODE,BIRTHDAY)
VALUES(SEQ_EMPLOYEE_NO.NEXTVAL,'최과장','R4','H1',SYSDATE);
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_RANK,DEPT_CODE,BIRTHDAY)
VALUES(SEQ_EMPLOYEE_NO.NEXTVAL,'나차장','R5','H1',SYSDATE);
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_RANK,DEPT_CODE,BIRTHDAY)
VALUES(SEQ_EMPLOYEE_NO.NEXTVAL,'조대리','R6','H1',SYSDATE);
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_RANK,DEPT_CODE,BIRTHDAY)
VALUES(SEQ_EMPLOYEE_NO.NEXTVAL,'하사원','R7','H1',SYSDATE);

INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_RANK,DEPT_CODE,BIRTHDAY)
VALUES(SEQ_EMPLOYEE_NO.NEXTVAL,'김부장','R2','S',SYSDATE);
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_RANK,DEPT_CODE,BIRTHDAY)
VALUES(SEQ_EMPLOYEE_NO.NEXTVAL,'오팀장','R3','S1',SYSDATE);
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_RANK,DEPT_CODE,BIRTHDAY)
VALUES(SEQ_EMPLOYEE_NO.NEXTVAL,'박과장','R4','S1',SYSDATE);
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_RANK,DEPT_CODE,BIRTHDAY)
VALUES(SEQ_EMPLOYEE_NO.NEXTVAL,'서차장','R5','S1',SYSDATE);
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_RANK,DEPT_CODE,BIRTHDAY)
VALUES(SEQ_EMPLOYEE_NO.NEXTVAL,'류대리','R6','S1',SYSDATE);
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_RANK,DEPT_CODE,BIRTHDAY)
VALUES(SEQ_EMPLOYEE_NO.NEXTVAL,'고사원','R7','S1',SYSDATE);

INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_RANK,DEPT_CODE,BIRTHDAY)
VALUES(SEQ_EMPLOYEE_NO.NEXTVAL,'안팀장','R3','S2',SYSDATE);
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_RANK,DEPT_CODE,BIRTHDAY)
VALUES(SEQ_EMPLOYEE_NO.NEXTVAL,'차과장','R4','S2',SYSDATE);
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_RANK,DEPT_CODE,BIRTHDAY)
VALUES(SEQ_EMPLOYEE_NO.NEXTVAL,'나차장','R5','S2',SYSDATE);
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_RANK,DEPT_CODE,BIRTHDAY)
VALUES(SEQ_EMPLOYEE_NO.NEXTVAL,'이대리','R6','S2',SYSDATE);
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_RANK,DEPT_CODE,BIRTHDAY)
VALUES(SEQ_EMPLOYEE_NO.NEXTVAL,'유사원','R7','S2',SYSDATE);


INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_RANK,DEPT_CODE,BIRTHDAY)
VALUES(SEQ_EMPLOYEE_NO.NEXTVAL,'유팀장','R3','P',SYSDATE);
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_RANK,DEPT_CODE,BIRTHDAY)
VALUES(SEQ_EMPLOYEE_NO.NEXTVAL,'정과장','R4','P',SYSDATE);
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_RANK,DEPT_CODE,BIRTHDAY)
VALUES(SEQ_EMPLOYEE_NO.NEXTVAL,'박차장','R5','P',SYSDATE);
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_RANK,DEPT_CODE,BIRTHDAY)
VALUES(SEQ_EMPLOYEE_NO.NEXTVAL,'전대리','R6','P',SYSDATE);
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_RANK,DEPT_CODE,BIRTHDAY)
VALUES(SEQ_EMPLOYEE_NO.NEXTVAL,'김사원','R7','P',SYSDATE);

INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_RANK,DEPT_CODE,BIRTHDAY)
VALUES(SEQ_EMPLOYEE_NO.NEXTVAL,'원팀장','R3','CS',SYSDATE);
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_RANK,DEPT_CODE,BIRTHDAY)
VALUES(SEQ_EMPLOYEE_NO.NEXTVAL,'이과장','R4','CS',SYSDATE);
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_RANK,DEPT_CODE,BIRTHDAY)
VALUES(SEQ_EMPLOYEE_NO.NEXTVAL,'정차장','R5','CS',SYSDATE);
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_RANK,DEPT_CODE,BIRTHDAY)
VALUES(SEQ_EMPLOYEE_NO.NEXTVAL,'장대리','R6','CS',SYSDATE);
INSERT INTO EMPLOYEE(EMP_NO,EMP_NAME,EMP_RANK,DEPT_CODE,BIRTHDAY)
VALUES(SEQ_EMPLOYEE_NO.NEXTVAL,'신사원','R7','CS',SYSDATE);


INSERT INTO COMMUTE_ON
VALUES(10001, TO_DATE('2024-12-29 오전 09:19:19', 'YYYY-MM-DD AM HH:MI:SS'));
INSERT INTO COMMUTE_ON
VALUES(10001, TO_DATE('2024-12-30 오전 08:30:34', 'YYYY-MM-DD AM HH:MI:SS'));
INSERT INTO COMMUTE_ON
VALUES(10003, TO_DATE('2024-12-29 오전 09:15:12', 'YYYY-MM-DD AM HH:MI:SS'));
INSERT INTO COMMUTE_ON
VALUES(10007, TO_DATE('2024-12-30 오전 08:45:23', 'YYYY-MM-DD AM HH:MI:SS'));
INSERT INTO COMMUTE_ON
VALUES(10010, TO_DATE('2024-12-31 오전 09:02:45', 'YYYY-MM-DD AM HH:MI:SS'));
INSERT INTO COMMUTE_ON
VALUES(10014, TO_DATE('2025-01-01 오전 08:58:30', 'YYYY-MM-DD AM HH:MI:SS'));
INSERT INTO COMMUTE_ON
VALUES(10017, TO_DATE('2025-01-02 오전 09:20:14', 'YYYY-MM-DD AM HH:MI:SS'));
INSERT INTO COMMUTE_ON
VALUES(10004, TO_DATE('2024-12-29 오전 09:05:39', 'YYYY-MM-DD AM HH:MI:SS'));
INSERT INTO COMMUTE_ON
VALUES(10021, TO_DATE('2025-01-02 오전 08:49:51', 'YYYY-MM-DD AM HH:MI:SS'));
INSERT INTO COMMUTE_ON
VALUES(10012, TO_DATE('2024-12-31 오전 09:10:03', 'YYYY-MM-DD AM HH:MI:SS'));
INSERT INTO COMMUTE_ON
VALUES(10009, TO_DATE('2024-12-30 오전 08:55:19', 'YYYY-MM-DD AM HH:MI:SS'));
INSERT INTO COMMUTE_ON
VALUES(10020, TO_DATE('2025-01-01 오전 09:18:41', 'YYYY-MM-DD AM HH:MI:SS'));
INSERT INTO COMMUTE_ON
VALUES(10005, TO_DATE('2025-01-03 오전 08:50:22', 'YYYY-MM-DD AM HH:MI:SS'));
INSERT INTO COMMUTE_ON
VALUES(10015, TO_DATE('2025-01-05 오전 09:05:37', 'YYYY-MM-DD AM HH:MI:SS'));
INSERT INTO COMMUTE_ON
VALUES(10018, TO_DATE('2025-01-07 오전 08:44:19', 'YYYY-MM-DD AM HH:MI:SS'));
INSERT INTO COMMUTE_ON
VALUES(10011, TO_DATE('2025-01-09 오전 09:13:56', 'YYYY-MM-DD AM HH:MI:SS'));
INSERT INTO COMMUTE_ON
VALUES(10022, TO_DATE('2025-01-10 오전 08:59:45', 'YYYY-MM-DD AM HH:MI:SS'));

--퇴근
INSERT INTO COMMUTE_OFF
VALUES(10001, TO_DATE('2024-12-29 오후 06:45:23', 'YYYY-MM-DD PM HH:MI:SS'));
INSERT INTO COMMUTE_OFF
VALUES(10001, TO_DATE('2024-12-30 오후 07:10:34', 'YYYY-MM-DD PM HH:MI:SS'));
INSERT INTO COMMUTE_OFF
VALUES(10003, TO_DATE('2024-12-29 오후 07:30:12', 'YYYY-MM-DD PM HH:MI:SS'));
INSERT INTO COMMUTE_OFF
VALUES(10007, TO_DATE('2024-12-30 오후 06:50:45', 'YYYY-MM-DD PM HH:MI:SS'));
INSERT INTO COMMUTE_OFF
VALUES(10010, TO_DATE('2024-12-31 오후 07:25:39', 'YYYY-MM-DD PM HH:MI:SS'));
INSERT INTO COMMUTE_OFF
VALUES(10014, TO_DATE('2025-01-01 오후 06:35:21', 'YYYY-MM-DD PM HH:MI:SS'));
INSERT INTO COMMUTE_OFF
VALUES(10017, TO_DATE('2025-01-02 오후 07:40:14', 'YYYY-MM-DD PM HH:MI:SS'));
INSERT INTO COMMUTE_OFF
VALUES(10004, TO_DATE('2024-12-29 오후 06:55:39', 'YYYY-MM-DD PM HH:MI:SS'));
INSERT INTO COMMUTE_OFF
VALUES(10021, TO_DATE('2025-01-02 오후 07:05:51', 'YYYY-MM-DD PM HH:MI:SS'));
INSERT INTO COMMUTE_OFF
VALUES(10012, TO_DATE('2024-12-31 오후 06:50:03', 'YYYY-MM-DD PM HH:MI:SS'));
INSERT INTO COMMUTE_OFF
VALUES(10009, TO_DATE('2024-12-30 오후 07:15:19', 'YYYY-MM-DD PM HH:MI:SS'));
INSERT INTO COMMUTE_OFF
VALUES(10020, TO_DATE('2025-01-01 오후 06:40:41', 'YYYY-MM-DD PM HH:MI:SS'));
INSERT INTO COMMUTE_OFF
VALUES(10005, TO_DATE('2025-01-03 오후 07:00:22', 'YYYY-MM-DD PM HH:MI:SS'));
INSERT INTO COMMUTE_OFF
VALUES(10015, TO_DATE('2025-01-05 오후 06:45:37', 'YYYY-MM-DD PM HH:MI:SS'));
INSERT INTO COMMUTE_OFF
VALUES(10018, TO_DATE('2025-01-07 오후 07:25:19', 'YYYY-MM-DD PM HH:MI:SS'));
INSERT INTO COMMUTE_OFF
VALUES(10011, TO_DATE('2025-01-09 오후 06:50:56', 'YYYY-MM-DD PM HH:MI:SS'));
INSERT INTO COMMUTE_OFF
VALUES(10022, TO_DATE('2025-01-10 오후 07:10:45', 'YYYY-MM-DD PM HH:MI:SS'));

--근태
INSERT INTO ATTEMDANCE_TYPE
VALUES(SEQ_ATNO.NEXTVAL, '반차');
INSERT INTO ATTEMDANCE_TYPE
VALUES(SEQ_ATNO.NEXTVAL, '월차');

--근태 세부
INSERT INTO ATTEMDANCE
VALUES(SEQ_ANO.NEXTVAL, 100, '2023연차', 1.0, DEFAULT);
INSERT INTO ATTEMDANCE
VALUES(SEQ_ANO.NEXTVAL, 100, '2022연차', 1.0, DEFAULT);

--사원 근태
INSERT INTO EMP_ATTEMDANCE
VALUES('2024/11/23', 1001, 10000, 2.0, DEFAULT, NULL);
INSERT INTO EMP_ATTEMDANCE
VALUES('2024/02/03', 1002, 10000, 1.0, DEFAULT, NULL);
INSERT INTO EMP_ATTEMDANCE
VALUES('2024/06/3', 1002, 10000, 1.0, DEFAULT, NULL);

INSERT INTO EMPLOYEE (EMP_NO, EMP_RANK, DEPT_CODE, EMP_NAME, VACATION)
VALUES (SEQ_EMPLOYEE_NO.NEXTVAL,'R7','H','김회원',13);
INSERT INTO EMPLOYEE (EMP_NO, EMP_RANK, DEPT_CODE, EMP_NAME, VACATION)
VALUES (SEQ_EMPLOYEE_NO.NEXTVAL,'R6','S','이유저',14);
INSERT INTO EMPLOYEE (EMP_NO, EMP_RANK, DEPT_CODE, EMP_NAME, VACATION)
VALUES (SEQ_EMPLOYEE_NO.NEXTVAL,'R5','P','홍길동',15);
INSERT INTO EMPLOYEE (EMP_NO, EMP_RANK, DEPT_CODE, EMP_NAME, VACATION)
VALUES (SEQ_EMPLOYEE_NO.NEXTVAL,'R6','H1','김유저',14);
INSERT INTO EMPLOYEE (EMP_NO, EMP_RANK, DEPT_CODE, EMP_NAME, VACATION)
VALUES (SEQ_EMPLOYEE_NO.NEXTVAL,'R7','P','이회원',13);



--결재 형식
set define off;
INSERT INTO APPROVE_DOCUMENT (DO_NO, DO_LIST, DO_CONTENT) VALUES ('1', '휴직원', '<div class="container"><h1>휴 가 신 청 서</h1><table class="vacation-table"><tr><th style="width: 20%;">소 속</th><td></td></tr><tr><th>성 명</th><td></td></tr><tr><th>직 위</th><td></td></tr><tr><th>종 류</th><td></td></tr><tr><th>사 유</th><td></td></tr><tr><th>기 간</th><td></td></tr><tr><th>비상연락망</th><td></td></tr></table><p style="text-align: center;">위와 같이 휴가를 신청하오니 승인하여 주시기 바랍니다.</p><div class="signature">20&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;년&nbsp;&nbsp;&nbsp;&nbsp;월&nbsp;&nbsp;&nbsp;&nbsp;일<br><br><div class="name">소 속: </div><div class="name">성 명:</div></div></div>');
INSERT INTO APPROVE_DOCUMENT (DO_NO, DO_LIST, DO_CONTENT) VALUES ('2', '비품신청서', '<div class="container"><h1>비 품 신 청 서</h1><table class="application-table"><tr class="header-row"><th>신청자</th><td colspan="4"></td></tr><tr class="header-row"><th>부서</th><td colspan="4"></td></tr><tr class="header-row"><th>신청일자</th><td colspan="4"></td></tr><tr class="menu"><th>no.</th><th>비품명</th><th>사용용도</th><th>수량</th><th>금액</th></tr><tr class="content"><td>1</td><td>필기구</td><td>부서 필기구</td><td>3ea</td><td>12,900</td></tr><tr class="content"><td></td><td></td><td></td><td></td><td></td></tr><tr class="content"><td></td><td></td><td></td><td></td><td></td></tr><tr class="content"><td></td><td></td><td></td><td></td><td></td></tr><tr class="content"><td></td><td></td><td></td><td></td><td></td></tr><tr class="content"><td></td><td></td><td></td><td></td><td></td></tr><tr class="content"><td></td><td></td><td></td><td></td><td></td></tr></table></div>');
INSERT INTO APPROVE_DOCUMENT (DO_NO, DO_LIST, DO_CONTENT) VALUES ('3', '차량운행일지', '<div class="container"><h1>차량운행일지</h1><div class="centered"><p>년 &nbsp;&nbsp; 월 &nbsp;&nbsp; 일 &nbsp;&nbsp; 요일</p></div><table class="vehicle-log-table"><thead><tr><th rowspan="2">차량번호</th><th colspan="2">출발</th><th colspan="2">도착</th><th rowspan="2">운행시간</th><th rowspan="2">주행거리</th><th rowspan="2">운행목적</th><th rowspan="2">사용자</th><th rowspan="2">비고</th></tr><tr><th>출발지</th><th>시간</th><th>도착지</th><th>시간</th></tr></thead><tbody><tr><td class="empty-cell"></td><td class="empty-cell"></td><td class="empty-cell"></td><td class="empty-cell"></td><td class="empty-cell"></td><td class="empty-cell"></td><td class="empty-cell"></td><td class="empty-cell"></td><td class="empty-cell"></td><td class="empty-cell"></td></tr></tbody></table><div class="margin-top"><p class="bold">정비예정내용</p><div class="repair-schedule"></div></div><div class="margin-top"><p class="bold">정비 및 시정사항</p><div class="repair-section"><div class="repair-content"></div><div class="repair-factory">정비공장</div></div></div><table class="vehicle-log-table"><tr><th>1일 운행시간</th><th>시간</th><th>분</th><th>총 주행 거리</th><th>km</th></tr><tr><td>연합도량</td><td></td><td></td><td></td><td></td></tr></table><p class="bold">비 고</p><div class="notes"></div></div>');
INSERT INTO APPROVE_DOCUMENT (DO_NO, DO_LIST, DO_CONTENT) VALUES ('5', '사직서', '<div class="container"><div class="title">사 직 서</div><table class="info-table"><tr><th>소 &nbsp;&nbsp;&nbsp;&nbsp;속 :</th><td></td></tr><tr><th>직 &nbsp;&nbsp;&nbsp;&nbsp;위 :</th><td></td></tr><tr><th>성 &nbsp;&nbsp;&nbsp;&nbsp;명 :</th><td></td></tr><tr><th>퇴사일자 :</th><td></td></tr><tr><th>사직사유 :</th><td><br><br><br><br></td></tr></table><div class="content">상기 본인은 위와 같은 사정으로 인하여  &nbsp;&nbsp;&nbsp;&nbsp;년 &nbsp;&nbsp;월 &nbsp;&nbsp;일 부로 <br>사직하고자 하오니 선처하여 주시기 바랍니다.<br><br></div><div class="footer"><div>신 청 인 : (인)</div></div></div>');
INSERT INTO APPROVE_DOCUMENT (DO_NO, DO_LIST, DO_CONTENT) VALUES ('4','출장보고서','<div class="report-container"><h1 style="text-align: center;">출장 보고서</h1><table class="report-table"><tr><th>소속</th><td class="w ic"></td><th>직위</th><td class="w ic"></td><th>성명</th><td class="w ic"></td><th>(인원)</th><td class="w ic-s"></td></tr><tr><th>출장기간</th><td colspan="7" class="w">년 월 일부터 ~ 년 월 일까지 ( 일간)</td></tr><tr><th>출장지</th><td colspan="7" class="w"></td></tr><tr><th>방문처</th><td colspan="7" class="w"></td></tr><tr><th>방문목적</th><td colspan="7" class="w"></td></tr><tr><th>숙박지</th><td colspan="7" class="w"></td></tr></table><table class="report-table"><thead><tr><th>(동행자)소속</th><th>직위</th><th>성명</th><th>출장비용 (항목)</th><th>출장비용 (금액)</th></tr></thead><tbody><tr><td class="ic"></td><td class="ic"></td><td class="ic"></td><td class="ic"></td><td class="ic-s"></td></tr><tr><td class="ic"></td><td class="ic"></td><td class="ic"></td><td class="ic"></td><td class="ic-s"></td></tr><tr><td class="ic"></td><td class="ic"></td><td class="ic"></td><td class="ic"></td><td class="ic-s"></td></tr><tr><td class="ic"></td><td class="ic"></td><td class="ic"></td><td class="ic"></td><td class="ic-s"></td></tr><tr><td colspan="4">합계</td><td class="ic-s"></td></tr></tbody></table><table class="report-table"><tr><th style="text-align: left;">기타사항</th></tr><tr><td class="w"><textarea style="width: 100%; height: 100px; border: none;"></textarea></td></tr></table></div>');

INSERT INTO approve_status (STATUS_CODE, STATUS) VALUES ('0', '대기');
INSERT INTO approve_status (STATUS_CODE, STATUS) VALUES ('1', '승인');
INSERT INTO approve_status (STATUS_CODE, STATUS) VALUES ('2', '거절');

commit;